# Introduction to Tensorflow

In [29]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## Tensors
Tensors are the generalization of matrices and vectors to higher dimensions. Each tensor has a data type and a shape.

**Data types** include float32, int32, string and others. 

Its **shape** represents the dimension of data.

### Example of Tensors

In [41]:
string = tf.Variable("Hello", tf.string)
number = tf.Variable(10, tf.int16)
floating = tf.Variable(1.23, tf.float64)

### Rank/Degree of Tensors

In [53]:
rank1_tensor = tf.Variable([1, 2, 3], tf.int16)
rank2_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int16)

In [54]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors

In [56]:
rank2_tensor.shape

TensorShape([2, 3])

### Changing Shape

In [ ]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)

tensor2 = tf.reshape(tensor1, [2, 3, 1]) # reshape tensor1 to shape [2, 3, 1]
print(tensor2)

tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                       # this will reshape the tensor to [3, 2]
print(tensor3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
These are the most commonly used types of tensors:
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of `Variable`, all of these tensors are immutable, meaning their value may not change during execution.

### Evaluating Tensors


In [62]:
with tf.Session() as sess: # creates a session using the default graph
    tensor.eval() # tensor will of course be the name of your tensor

AttributeError: module 'tensorflow' has no attribute 'Session'

In the code above, we evaluated the tensor variable that was stored in the **default graph**. The default graph holds all operations not specified to any other graph. It is possible to create our own seperate graphs but for now we will stick with the default.

## Examples

In [65]:
t = tf.zeros([5, 5, 5, 5])

t = tf.reshape(t, [125,-1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]